name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_and_test:
    name: Build and Test with Node.js v22
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js v22
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: npm

      - run: npm ci

      - name: Build the project
        run: npm run build

      - name: Lint the code
        run: npm run lint

      - name: Type-check the code
        run: npm run check-types

      - name: Run unit tests with coverage
        run: npm run test -- --coverage

      - name: Install Playwright dependencies
        run: npx playwright install --with-deps

      - name: Run E2E tests
        run: npm run test:e2e

      - if: github.event_name == 'pull_request'
        name: Validate commit messages
        run: npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose
